[package]
name = "fieldide-editor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
ropey.workspace = true
tempfile.workspace = true
unicode-segmentation.workspace = true

[dev-dependencies]
tempfile.workspace = true

[lints]
workspace = true

