[package]
name = "fieldide-tui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
clap.workspace = true
crossterm.workspace = true
fieldide-adapters = { path = "../fieldide-adapters" }
fieldide-core = { path = "../fieldide-core" }
fieldide-editor = { path = "../fieldide-editor" }
ratatui.workspace = true
tokio.workspace = true
unicode-segmentation.workspace = true
unicode-width.workspace = true

[lints]
workspace = true
